### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by daogangtang** [thehydroimpulse/nanomsg.rs#104]
does this project to track the latest rust version?

**Comment by blabaere** [comment]
@daogangtang Yes, we plan to follow the nightly builds until rust 1.0.0 is out.
The master does not build currently, waiting for PR #102 to be merged.
@thehydroimpulse Do you see anything that would prevent #102 from being merged as it is now ?

**Comment by thehydroimpulse** [comment]
@blabaere Sorry for the delay, just merged that PR now.

**Comment by blabaere** [comment]
@thehydroimpulse No problem, I'll have a look at #103 and see if Travis thinks we can make one more person a little bit happier.

**Comment by blabaere** [comment]
@daogangtang PR  #102 merged, the master now builds with the current rust nightly.

**Comment by daogangtang** [comment]
+1.
