### ISSUE TITLE
Is it possible to not buffer received messages and only hold onto the last one that was received?

### ISSUE THREAD

**Issue by mitchmindtree** [thehydroimpulse/nanomsg.rs#136]
I'm working on a real-time AV app with a friend (I send audio data, he receives it and maps it to visuals). It seems that the receiving end is buffering each of the messages ensuring that every single message that was sent is being processed, however we would prefer that the receiver only stored the last message that was received (rather than buffering all of them) - is this possible with nanomsg? Any help appreciated :)

**Comment by blabaere** [comment]
@mitchmindtree @thehydroimpulse 

I'm afraid this kind of behavior is not implemented in any of the protocols available in nanomsg. But it should not be too hard to come up with a simple solution using nanomsg as it is. What you need here looks like a regular Push/Pull protocol where a thread on the Pull side would call  ```socket::recv``` continuously, storing only one message and making it available.

I also suggest that you ask the question on nanomsg's [mailing list](mailto:nanomsg@freelists.org) or [gitter chatroom](https://gitter.im/nanomsg/nanomsg). You'll have your question heard by experts there. Please see also the nanomsg's [community page](http://nanomsg.org/community.html).

By the way, if dropping messages from times to times is acceptable, maybe UDP would fit your need better, depending on your system's environment.

**Comment by mitchmindtree** [comment]
Thanks a lot @blabaere! After some searching around we decided that UDP would indeed be the better option for us, so we've decided to go with OSC instead as it's probably better suited to our situation.
