### ISSUE TITLE
Violation of `Read` contract for socket

### ISSUE THREAD

**Issue by netvl** [thehydroimpulse/nanomsg.rs#142]
The current `Read::read()` implementation on the socket returns not the number of bytes read into the buffer, but the length of the received message instead:
```rust
        let ret = unsafe { nanomsg_sys::nn_recv(self.socket, c_buf_ptr, buf_len, 0) };
        ...
        Ok(ret as usize)
```

However, this directly violates the requirement of `Read::read()` method which specifies that returned value must be between `0` and `buf.len()`:

> If the return value of this method is `Ok(n)`, then it must be guaranteed that `0 <= n <= buf.len()`. A nonzero n value indicates that the buffer `buf` has been filled in with `n` bytes of data from this source.

This behavior causes other library functions to behave funnily, for example, on some inputs `Read::read_to_end()` method will panic:

    thread '<main>' panicked at 'slice index starts at 50 but ends at 32', ../src/libcore/slice.rs:521
    stack backtrace:
       1:     0x55c7c7330aa0 - sys::backtrace::tracing::imp::write::h188951552cfde9c3tnu
       2:     0x55c7c7332f35 - panicking::default_handler::_<closure>::closure.42740
       3:     0x55c7c7332b04 - panicking::default_handler::h00ef84220a33c4b5VEy
       4:     0x55c7c7328c76 - sys_common::unwind::begin_unwind_inner::h48700dfae980863d0ft
       5:     0x55c7c7329138 - sys_common::unwind::begin_unwind_fmt::h63b701b0b99330e96et
       6:     0x55c7c73300e1 - rust_begin_unwind
       7:     0x55c7c736048f - panicking::panic_fmt::h48ff011da22960abnYL
       8:     0x55c7c7360683 - slice::slice_index_order_fail::habfbe78d9c8ed56cAIP
       9:     0x55c7c7187405 - slice::_[T].ops..IndexMut<ops..Range<usize>>::index_mut::h9687962521054386141
                            at ../src/libcore/slice.rs:576
      10:     0x55c7c71873b5 - slice::_[T].ops..IndexMut<ops..RangeFrom<usize>>::index_mut::h18389987896732851381
                            at ../src/libcore/slice.rs:600
      11:     0x55c7c718bd63 - vec::Vec<T>.ops..IndexMut<ops..RangeFrom<usize>>::index_mut::h14423825064217593855
                            at ../src/libcollections/vec.rs:1203
      12:     0x55c7c718b296 - io::read_to_end::h2539968164754978770
                            at ../src/libstd/io/mod.rs:359
      13:     0x55c7c718b0d3 - io::Read::read_to_end::h16184372645381771208
                            at ../src/libstd/io/mod.rs:522

**Comment by blabaere** [comment]
Fixed in version 0.5.0, thanks for spotting this.

**Comment by netvl** [comment]
I'm just curious, since it is not in this git repository, is there another, more recent fork?

**Comment by blabaere** [comment]
I usually merge my changes into this repository but not always in "real-time". I will probably do it this week after fixing the appveyor build script. You can see the changes here : https://github.com/blabaere/nanomsg.rs

**Comment by netvl** [comment]
Ok, thanks for the explanation!

**Comment by blabaere** [comment]
PR #144 : Merge done.
