### ISSUE TITLE
Consider using pkg-config for locating nanomsg native library

### ISSUE THREAD

**Issue by netvl** [thehydroimpulse/nanomsg.rs#143]
Lots of FFI bindings in Rust use pkg-config to locate native libraries, here are only few:
* [git2-rs](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/build.rs#L29)
* [curl-rust](https://github.com/carllerche/curl-rust/blob/master/curl-sys/build.rs#L32)
* [rust-openssl](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs#L17)
* [rust-sdl2](https://github.com/AngryLawyer/rust-sdl2/blob/master/sdl2-sys/build.rs#L17)
* [libusb-sys](https://github.com/dcuddeback/libusb-sys/blob/master/build.rs#L4)

nanomsg itself provides a pkg-config descriptor, for example, after `brew install nanomsg` I get this:
```
% pkg-config --libs libnanomsg
-L/usr/local/Cellar/nanomsg/0.8-beta/lib -lnanomsg
```

Therefore, it would be natural for nanomsg.rs to use it as well.

**Comment by blabaere** [comment]
Nanomsg 0.9 build system has changed to cmake, and I struggled a bit to get nanomsg.rs tests to run.
Until I recalled this pending issue, and using the above command line solved my problem.
So maybe now is a good time to start using pkg-config.

**Comment by photex** [comment]
With #151 I've included the most basic usage of the pkg_config crate for build scripts. At fist glance, it seems to have interacted badly with the travis config. If someone wouldn't mind trying this locally as well that'd be helpful.

**Comment by blabaere** [comment]
For pkg_config to work correctly, the Makefile must be updated to build libnanomsg from source and a `sudo ldconfig` must be added after the last `cmake` call. This should be fixed soon.

**Comment by blabaere** [comment]
Done, thanks to @photex !
