### ISSUE TITLE
can not build at debian 

### ISSUE THREAD

**Issue by ksaritek** [thehydroimpulse/nanomsg.rs#163]
error[E0252]: a value named `ENOTSUP` has already been imported in this module
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/nanomsg-sys-0.6.0/src/lib.rs:7:9
  |
5 | pub use libc::*;
  |         -------- previous import of `ENOTSUP` here
6 |
7 | pub use posix_consts::*;
  |         ^^^^^^^^^^^^^^^^ already imported

error[E0255]: a value named `ENOTSUP` has already been imported in this module
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/nanomsg-sys-0.6.0/src/lib.rs:85:5
   |
72 |     use libc::*;
   |         -------- previous import of `ENOTSUP` here
...
85 |     pub const ENOTSUP: c_int = NN_HAUSNUMERO + 1;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `ENOTSUP` was already imported

error: aborting due to 2 previous errors

**Comment by blabaere** [comment]
It seems that the lastest libc brings some changes, and some constants don't need to be redefined anymore. So i tried removing this extra `ENOTSUP` from non-windows build and it's working on my ubuntu machine and on travis. Could you please try to build [my fork](https://github.com/blabaere/nanomsg.rs) on your debian system and let me know if it works any better ? If the changes fix your build problem I'll get it merged.

Regards,
Benoît

**Comment by vityafx** [comment]
I have this problem too now, on my debian vds. I has pointed my project dependency to @blabaere's fork of nanomsg, it now compiles fine. However, this should be done in upstream in my opinion.

**Comment by blabaere** [comment]
I was waiting for someone to confirm the fix correctness, now it's done I will get it merged.

**Comment by blabaere** [comment]
@ksaritek @vityafx Warning: shameless self-promotion ! Did I mentioned I was working on a 100% Rust implementation of nanomsg ? Yes I just did : https://github.com/blabaere/scaproust

**Comment by ksaritek** [comment]
sorry for being late, it is working fine. 
I will have a look at that.

**Comment by vityafx** [comment]
@blabaere Did you compare the performance?

**Comment by blabaere** [comment]
@vityafx There is no benchmark yet since the priority was feature completeness and correct behavior. I guess there is enough working stuff in version 0.2 to start working on this. On the other hand, the current design was thought with performance in mind so that optimizations should not require a massive rewrite.

May I ask where your performance focus is : latency or throughput ?

**Comment by blabaere** [comment]
@ksaritek No problem, there was no deadline and thank you for your interest.

**Comment by vityafx** [comment]
> May I ask where your performance focus is : latency or throughput ?
@blabaere Honestly, both of them :)

**Comment by vityafx** [comment]
> May I ask where your performance focus is : latency or throughput ?
@blabaere Honestly, both of them :) I should say, I don't use it much yet, but there will be a need probably. And I ask that more because of curiosity.

**Comment by blabaere** [comment]
I have adapted the original nanomsg performance measurement utilities and ran both version.
The report is [available here](https://github.com/blabaere/scaproust/tree/master/perf).
If I find some time one day I may port the tools to nanomsg.rs too.

**Comment by vityafx** [comment]
@blabaere Not bad. And there is a way to go. Keep this measures update please.

**Comment by blabaere** [comment]
@vityafx I fixed a naive use of poll registration, ran the measurement utilities again and updated the report. I guess this is first and last time I will get this kind of impact with a single change.
