### ISSUE TITLE
Is the PubSub example supposed to work?

### ISSUE THREAD

**Issue by Enet4** [thehydroimpulse/nanomsg.rs#173]
I could not get the example in pubsub.rs (added by #109) to work as expected.
As explained in [this SO question](http://stackoverflow.com/q/42906463/1233251), which I managed to reproduce in my Linux system, we spawned a device, a client and a server, in this order, under the same topic. Although we would expect the client to receive the published messages, no message arrives there.
Changing the IPC socket addresses to a relative address in the file system didn't help either, even though I can see that the two socket files were created.
Do you happen to know what could be wrong here? Since the pubsub and device tests pass, I find this quite odd.

**Comment by blabaere** [comment]
It used to work, and does not work anymore. I'll have a look and try to find out what's going on. Thanks for taking time to report the problem.

**Comment by blabaere** [comment]
First result of the investigation: using "" as topic argument for client and device options allows the client to receive the messages published by the server. Still investigating ... 

Device:
```bash
~/dev/nanomsg.rs/target/debug/examples$ ./pubsub device ""
Subscribed to '[]'.
Device is ready.
```

Server:
```bash
~/dev/nanomsg.rs/target/debug/examples$ ./pubsub server toto
Server is ready.
Published '[116, 111, 116, 111] #1'.
Published '[116, 111, 116, 111] #2'.
Published '[116, 111, 116, 111] #3'.
Published '[116, 111, 116, 111] #4'.
```

Client:
```bash
~/dev/nanomsg.rs/target/debug/examples$ ./pubsub client ""
Subscribed to '[]'.
Recv '[116, 111, 116, 111] #2'.
Recv '[116, 111, 116, 111] #3'.
```

**Comment by blabaere** [comment]
@Enet4 
Found it ! The server is not creating the messages correctly. The formatter is creating a buffer with the ascii codes of each topic character, separated by commas and surrounded by square brackets ...
I'll fix this.

**Comment by blabaere** [comment]
The above commit fixes the issue. It makes the server create a message by concatenating the topic with a variable suffix. Instead of trying to format a byte slice as a string.
