### ISSUE TITLE
Build warning for nanomsg-sys

### ISSUE THREAD

**Issue by stusmall** [thehydroimpulse/nanomsg.rs#176]
Compiling nanomsg-sys v0.6.1 (file:///home/stusmall/Workspace/Upstream/nanomsg.rs/nanomsg_sys)
warning: redundant linker flag specified for library `nanomsg`

I took a quick look at this and it's generated from the "pkg_config::find_library("nanomsg")" in build.rs but not sure why.  I didn't dig into it much after that.

**Comment by blabaere** [comment]
It seems that both the link attribute and the pkg-config are generating the command line link option. I'll remove the one for "non-bundled" builds.

**Comment by stusmall** [comment]
Wow.  Thanks for the quick patch.  It clears up the issue for me.
