### ISSUE TITLE
How to use REQREP without Device?

### ISSUE THREAD

**Issue by mrLSD** [thehydroimpulse/nanomsg.rs#181]
I look to example: https://github.com/thehydroimpulse/nanomsg.rs/blob/master/examples/reqrep.rs

And I have several questions:
* Why I should open 2 different sockets for client and server?
* How to connect as client to server directly without Device layer? It's unclear why I should use aditional layer for client and server. Why I should use different sockets.

**Comment by blabaere** [comment]
Hi,

The example shows how to setup a device. In this configuration, there is a client with one socket (REQ), a server with one socket (REP), and the device which has two sockets (REQ + REP). The device is used to introduce an indirection between server and client.

But it can work with only a client (REQ) and a server (REP). You'll find an [example (in C) here](http://nanomsg.org/gettingstarted/index.html).

Regards,
Benoît

**Comment by mrLSD** [comment]
As you can see:
http://nanomsg.org/gettingstarted/index.html#_request_reply_i_ask_you_answer

It's no example for REQREP. For REQREP example author copied Pipeline example.

Possibly for Rust good example will be Rust code but not C.

**Comment by blabaere** [comment]
I added a [unit test](https://github.com/thehydroimpulse/nanomsg.rs/blob/15c86848f57aa5c600efa5e9d46fa2a4dc0d9e8f/src/lib.rs#L1642) with one Req socket and one Rep socket where they exchange a request and a reply.
