### ISSUE TITLE
plan to be ready for 1.0?

### ISSUE THREAD

**Issue by buster** [thehydroimpulse/nanomsg.rs#89]
Just wondering if this library will be supported with 1.0?
Currently it doesn't build...

**Comment by blabaere** [comment]
We definitely plan to be ready for 1.0 and ome work has already be done to support the last two nightlies (2015-01-06 and 2015-01-08). This is currently building but has not been merged yet. You can check it here : https://github.com/blabaere/nanomsg.rs.

**Comment by buster** [comment]
Oh, that's great, i was eagerly waiting for some activity here, thanks! :)
